"""Generate every figure the paper uses.

    python3 scripts/paper_figures.py                  # all figures
    python3 scripts/paper_figures.py stochastic       # any whose name contains a token
"""

import shutil
import sys
from functools import partial
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))  # repo root, so vo_utils imports

import numpy as np
import matplotlib.pyplot as plt

from minkowski_utils import Circle
from vo_utils import CROSSING, Scenario, Ship, VelocityObstacle, sample_cpa, uniform_like
from vo_utils.plotting import (
    equivalence_figure, stochastic_comparison_figure, class_limits,
    _cpa_fields, _frame, _frame_samples, _vo_membership,
)

OUT = Path(__file__).resolve().parent.parent / "artifacts" / "paper"
FIG = OUT / "figures"
SEED = 0
DPI = 200

# ---- Equivalence figure --------------------------------------------------------------
RADIUS = 10.0                    # per ship, so R = 20
RELPOS = np.array([48.0, 36.0])  # target relative to own
V_TARGET = np.array([-4.0, 2.0])
D_FRAC = 0.6                     # miss distance as a fraction of R: a grazing conflict
SPEED = 10.0                     # closing speed ||v_rel|| of the twin pair
EQUIV_N = 8_000                  # candidate velocities, shared by all three panels
EQUIV_PAD = 0.25                 # frame padding; also the sampling window
MARK_SIZE = 3.0                  # matplotlib scatter mark area (review PNG only)
SHADE_LEVELS = 4                 # discrete magnitude shades per class in the TikZ figure

# ---- Stochastic comparison -----------------------------------------------------------
# The same noise for every encounter
SIGMA_POS = 5.0                  # m,   = 0.25 R
SIGMA_VEL = 0.5                  # m/s
STOCH_N = 5_000                  # samples per encounter. Captions quote P[collision] to two
                                 # decimals: at 5k its Monte-Carlo sd is ~0.005
HIST_BINS = 80

COLLINEAR_CLOSING = Scenario("collinear_closing", (0, 0), (0, 5.0), (0, 120), (0, 4.5))
PAIR = (CROSSING, COLLINEAR_CLOSING)


def noise_models():
    """Per-channel (position, velocity) noise for each stochastic figure.

    The uniform ellipse is sized to a Gaussian level set: ``uniform_like`` gives semi-axes
    of 2 sigma, so its hard edge is exactly the Gaussian 2-sigma ellipse -- and a uniform
    ellipse of semi-axis 2 sigma also has per-axis variance sigma^2, so the two models
    carry the same covariance. Only the *shape* of the distribution differs. Here that is
    a disc of radius 10 m in position and 1 m/s in velocity.
    """
    Sp, Sv = SIGMA_POS ** 2 * np.eye(2), SIGMA_VEL ** 2 * np.eye(2)
    return {
        "gaussian": (Sp, Sv),
        "uniform_ellipse": (uniform_like(Sp, "ellipse"), uniform_like(Sv, "ellipse")),
    }


def twin_pair(relpos, v_target, R, d_frac=D_FRAC, speed=SPEED):
    """Two own velocities with equal DCPA and opposite-sign TCPA.

    Tilting the straight-at relative direction by ``asin(d / ||p_rel||)`` sets the miss
    distance to ``d``; negating the relative velocity reverses time, which preserves DCPA
    (it depends on the *line*) and flips the sign of TCPA.
    """
    p = np.asarray(relpos, dtype=float)
    dist = float(np.linalg.norm(p))
    phi = np.arcsin(d_frac * R / dist)
    ct, st = np.cos(phi), np.sin(phi)
    u = (-p / dist) @ np.array([[ct, st], [-st, ct]])
    w = speed * u
    return np.asarray(v_target) - w, np.asarray(v_target) + w


# ======================================================================================
# TikZ output helpers
# ======================================================================================

def _table(path, header, cols, ints=0):
    """Write one CSV table: float columns to 3 decimals, the last ``ints`` columns as integers."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fmt = ["%.3f"] * (len(cols) - ints) + ["%d"] * ints
    np.savetxt(path, np.column_stack(cols), delimiter=",", header=",".join(header),
               comments="", fmt=fmt)


def _clear_csvs(folder):
    """Remove a data folder's old CSVs, so a format change leaves no stale files behind."""
    if folder.exists():
        for f in folder.glob("*.csv"):
            f.unlink()


def _values(path, note, macros):
    """Write the generated numbers as \\def macros. Loaded inside the tikzpicture, so local."""
    lines = [f"% {note}",
             "% Generated by scripts/paper_figures.py and overwritten on every run -- don't edit.",
             "% Change look and layout in vo_style.tex and the figure's .tex instead."]
    for k, v in macros.items():
        text = f"{v:.4f}" if isinstance(v, (float, np.floating)) else str(v)
        lines.append(f"\\def\\{k}{{{text}}}")
    path.write_text("\n".join(lines) + "\n")


def _shade_levels(mag, holds):
    """Shade level per point, 0 (small) .. SHADE_LEVELS-1 (large), per class.

    Uses the matplotlib figure's own per-class percentile limits (``class_limits``), so the
    TikZ shading and the review render cannot drift apart.
    """
    lv = np.zeros(len(mag), int)
    for sel, (lo, hi) in zip((~holds, holds), class_limits(mag, holds)):
        t = np.clip((mag[sel] - lo) / max(hi - lo, 1e-12), 0.0, 1.0)
        lv[sel] = np.minimum((t * SHADE_LEVELS).astype(int), SHADE_LEVELS - 1)
    return lv


# ======================================================================================
# Figures: each writes its review PNG *and* its TikZ data, from one draw
# ======================================================================================

def fig_equivalence():
    own = Ship((0.0, 0.0), (0.0, 0.0), Circle(RADIUS))
    target = Ship(RELPOS, V_TARGET, Circle(RADIUS))
    R = 2.0 * RADIUS
    vc, vs = twin_pair(RELPOS, V_TARGET, R)

    fig = equivalence_figure(own, target, vc, vs, pad_frac=EQUIV_PAD, n_samples=EQUIV_N,
                             seed=SEED, mark_size=MARK_SIZE)

    # The identical draw: same frame, seed and n as the figure.
    c, half = _frame([(0.0, 0.0), V_TARGET, vc, vs], EQUIV_PAD)
    pts = _frame_samples(c, half, EQUIV_N, np.random.default_rng(SEED))
    truth = _vo_membership(pts, RELPOS, V_TARGET, R)          # Thm. 1's LHS, solved directly
    tcpa, dcpa = _cpa_fields(pts, RELPOS, V_TARGET)
    tau_pair, d_pair = _cpa_fields(np.stack([vc, vs]), RELPOS, V_TARGET)
    tests = {"a": (dcpa <= R, dcpa), "b": (tcpa > 0, np.abs(tcpa)),
             "c": ((dcpa <= R) & (tcpa > 0), None)}
    wrong = {k: int((h & ~truth).sum()) for k, (h, _) in tests.items()}

    # ---- TikZ data: one table, every sample once ------------------------------------
    # All three panels plot the same points, each colored by its own criterion, so the
    # table carries one class code per panel: tens digit 1 = the condition holds, 0 = it
    # fails; units digit = magnitude shade level (0 = smallest). In the .tex, each \addplot
    # keeps the rows with its code.
    out = FIG / "equivalence"
    _clear_csvs(out)
    codes = {key: 10 * holds.astype(int) + (0 if mag is None else _shade_levels(mag, holds))
             for key, (holds, mag) in tests.items()}
    _table(out / "samples.csv", ["x", "y", "dcpa", "tcpa", "code_a", "code_b", "code_c"],
           [pts[:, 0], pts[:, 1], dcpa, tcpa, codes["a"], codes["b"], codes["c"]], ints=3)

    # ---- TikZ geometry: every line is closed form, handed over as endpoints --------
    # Endpoints in axis units rather than TikZ polar coordinates: inside a pgfplots axis a
    # polar radius is in canvas units, which draws a correctly angled line in the wrong place.
    theta = np.arcsin(R / np.linalg.norm(RELPOS))
    los = np.arctan2(RELPOS[1], RELPOS[0])
    edges = [np.array([np.cos(los + s * theta), np.sin(los + s * theta)]) for s in (1, -1)]
    along = np.array([-RELPOS[1], RELPOS[0]]) / np.linalg.norm(RELPOS)   # TCPA = 0 line
    L = 4.0 * half                                                        # past the frame
    vO = V_TARGET
    macros = {"xmin": c[0] - half, "xmax": c[0] + half, "ymin": c[1] - half, "ymax": c[1] + half,
         "apexX": vO[0], "apexY": vO[1],
              # the closed forms the endpoints come from; see figures/README.md
              "pRelX": RELPOS[0], "pRelY": RELPOS[1],
              "pRelNorm": float(np.linalg.norm(RELPOS)), "safetyR": R,
              "coneHalfAngleDeg": float(np.degrees(theta)),
              "losBearingDeg": float(np.degrees(los)),
              "edgeOneBearingDeg": float(np.degrees(los + theta)),
              "edgeTwoBearingDeg": float(np.degrees(los - theta)),
              "tcpaLineA": RELPOS[0], "tcpaLineB": RELPOS[1],
              "tcpaLineC": float(RELPOS @ vO)}
    for name, e in zip(("One", "Two"), edges):
        a, b = vO - L * e, vO + L * e
        macros |= {f"bow{name}Ax": a[0], f"bow{name}Ay": a[1], f"bow{name}Bx": b[0], f"bow{name}By": b[1],
              f"cone{name}X": b[0], f"cone{name}Y": b[1]}
    a, b = vO - L * along, vO + L * along
    macros |= {"tcpaAx": a[0], "tcpaAy": a[1], "tcpaBx": b[0], "tcpaBy": b[1],
          "apprX": vc[0], "apprY": vc[1], "recX": vs[0], "recY": vs[1],
          "apprDcpa": f"{d_pair[0]:.1f}", "recDcpa": f"{d_pair[1]:.1f}",
          "apprTcpa": f"{tau_pair[0]:+.1f}", "recTcpa": f"{tau_pair[1]:+.1f}"}
    _values(out / "values.tex", "Equivalence figure: frame, closed-form lines, twin pair.", macros)

    caption = (f"Marks are {EQUIV_N:,} candidate velocities drawn uniformly over the plotted "
               f"range. Used as a test of VO membership, DCPA <= R alone is wrong on "
               f"{wrong['a']:,} of them and TCPA > 0 alone on {wrong['b']:,}; together they "
               f"are wrong on {wrong['c']}.")
    (out / "caption_numbers.txt").write_text(caption + "\n")

    return fig, [
        f"twin pair: DCPA {d_pair[0]:.1f} / {d_pair[1]:.1f} m, "
        f"TCPA {tau_pair[0]:+.1f} / {tau_pair[1]:+.1f} s",
        f"used as a VO test, wrong on: DCPA<=R {wrong['a']}/{EQUIV_N}, "
        f"TCPA>0 {wrong['b']}/{EQUIV_N}, both {wrong['c']}/{EQUIV_N}",
    ]


def _square_frame(points, pad_frac=0.18):
    """Square (center, half-width) framing ``points`` -- the matplotlib panel's rule."""
    P = np.asarray(points, dtype=float)
    lo, hi = P.min(axis=0), P.max(axis=0)
    return 0.5 * (lo + hi), max(0.5 * float((hi - lo).max()) * (1 + pad_frac), 1e-6)


def fig_stochastic(model):
    pos, vel = noise_models()[model]
    fig = stochastic_comparison_figure(PAIR, pos, vel, n=STOCH_N, seed=SEED)

    out = FIG / f"stochastic_{model}"
    _clear_csvs(out)
    macros, notes, caption, samples, hists = {}, [], [], [], []
    for row, (sc, tag) in enumerate(zip(PAIR, ("rowA", "rowB"))):   # the figure's seeds
        own, target = sc.ships()
        m = sc.metrics()
        R = m.safety_radius
        s = sample_cpa(own, target, pos, vel, n=STOCH_N, rng=np.random.default_rng(SEED + row))
        tau, d = s.tcpa, s.dcpa
        hit = (np.abs(d) <= R) & (tau >= 0)
        p_hit = float(hit.mean())

        # joint panel: the matplotlib limits (robust percentiles, DCPA symmetric about 0)
        xlo, xhi = np.percentile(tau, [0.5, 99.5])
        xpad = 0.05 * (xhi - xlo + 1e-9)
        xlo, xhi = xlo - xpad, xhi + xpad
        ymax = 1.05 * float(np.percentile(np.abs(d), 99.5))
        # Histograms are binned here rather than by pgfplots: its hist filter ignores row
        # selection, and it cannot draw the sideways marginal. group = 10*row + (0 TCPA, 1 DCPA)
        for var, data, lo, hi in ((0, tau, xlo, xhi), (1, d, -ymax, ymax)):
            dens, edges = np.histogram(data, bins=HIST_BINS, range=(lo, hi), density=True)
            hists.append(np.column_stack([np.full(edges.size, 10 * (row + 1) + var),
                                          edges, np.append(dens, dens[-1])]))

        # velocity panel: each sample's equivalent own velocity
        vown = np.asarray(target.vel) - s.relvel
        p1, p99 = np.nanpercentile(vown, [1, 99], axis=0)
        vel_center, vel_half = _square_frame([target.vel, own.vel, p1, p99])
        # every sample once: code = 10*row + collision (0 no, 1 yes). Panels keep their own
        # rows and discard samples outside their axis range, so TCPA tails never reach TeX.
        samples.append(np.column_stack([tau, d, vown[:, 0], vown[:, 1],
                                        10 * (row + 1) + hit.astype(int)]))
        apex = np.asarray(target.vel, float)
        e1, e2 = VelocityObstacle.from_ships(own, target).cone.edges

        det = (m.TCPA() > 0) and (abs(m.DCPA()) <= R)
        macros |= {f"{tag}name": sc.name.replace("_", " "), f"{tag}R": R,
              f"{tag}jxmin": xlo, f"{tag}jxmax": xhi, f"{tag}jymin": -ymax, f"{tag}jymax": ymax,
              f"{tag}tcpa": m.TCPA(), f"{tag}dcpa": m.DCPA(),
              f"{tag}ntcpa": f"{m.TCPA():.0f}", f"{tag}ndcpa": f"{abs(m.DCPA()):.0f}",
              f"{tag}verdict": "in VO" if det else "outside VO", f"{tag}P": f"{p_hit:.2f}",
              f"{tag}vxmin": vel_center[0] - vel_half, f"{tag}vxmax": vel_center[0] + vel_half,
              f"{tag}vymin": vel_center[1] - vel_half, f"{tag}vymax": vel_center[1] + vel_half,
              f"{tag}apexX": apex[0], f"{tag}apexY": apex[1],
              f"{tag}pRelNorm": float(np.linalg.norm(m.relpos)),
              f"{tag}coneHalfAngleDeg": float(np.degrees(np.arcsin(R / np.linalg.norm(m.relpos)))),
              f"{tag}losBearingDeg": float(np.degrees(np.arctan2(m.relpos[1], m.relpos[0]))),
              f"{tag}ownX": own.vel[0], f"{tag}ownY": own.vel[1],
              f"{tag}coneOneX": apex[0] + 4 * vel_half * e1[0], f"{tag}coneOneY": apex[1] + 4 * vel_half * e1[1],
              f"{tag}coneTwoX": apex[0] + 4 * vel_half * e2[0], f"{tag}coneTwoY": apex[1] + 4 * vel_half * e2[1]}

        t1, t99 = np.percentile(tau, [1, 99])
        notes.append(f"{sc.name:18s} P[collision] {p_hit:.2f}   "
                     f"TCPA 1-99%: [{t1:.0f}, {t99:.0f}] s")
        caption.append(f"{sc.name.replace('_', ' ')}: P[collision] = {p_hit:.2f}")

    sample_table, hist_table = np.vstack(samples), np.vstack(hists)
    _table(out / "samples.csv", ["tcpa", "dcpa", "vE", "vN", "code"],
           [sample_table[:, c] for c in range(5)], ints=1)
    _table(out / "histograms.csv", ["edge", "density", "group"],
           [hist_table[:, 1], hist_table[:, 2], hist_table[:, 0]], ints=1)
    _values(out / "values.tex", f"Stochastic comparison, {model.replace('_', ' ')} noise.", macros)
    (out / "caption_numbers.txt").write_text(
        f"{STOCH_N:,} samples per encounter. " + "; ".join(caption) + ".\n")
    return fig, notes


FIGURES = {
    "equivalence_sampled": fig_equivalence,
    "stochastic_comparison_gaussian": partial(fig_stochastic, "gaussian"),
    "stochastic_comparison_uniform_ellipse": partial(fig_stochastic, "uniform_ellipse"),
}


# ======================================================================================
# Hand-editable TikZ files. Written each run so the repo copy stays current; once uploaded,
# edits happen in Overleaf -- re-upload only the data folders when the data changes.
# ======================================================================================

TEMPLATES = Path(__file__).resolve().parent / "paper_tex"   # the .tex files copied to FIG
HANDOFF = TEMPLATES / "handoff"                             # README and captions for the package
PDFS = OUT / "pdf"          # figures compiled inside a copy of the paper (separate LaTeX run)
PACKAGE = OUT / "handoff_package"


def write_tikz_templates():
    """Copy the hand-editable TikZ files next to the generated data.

    They live in ``scripts/paper_tex/`` as real .tex, so they read and diff as LaTeX rather
    than as Python strings. Once uploaded, edits happen in Overleaf; re-upload only the
    data folders.
    """
    FIG.mkdir(parents=True, exist_ok=True)
    for src in sorted(TEMPLATES.iterdir()):
        if src.is_file():                      # paper_tex/handoff/ holds the package docs
            (FIG / src.name).write_text(src.read_text())


def _data_dictionary():
    """Describe every CSV column, read from the files themselves so it cannot go stale."""
    lines = ["# The data", "",
             "One row per sample. `code` (and `code_a/b/c`) says which point series a row",
             "belongs to, so one table serves every series in a figure:", "",
             "| code | meaning |", "|---|---|",
             "| `0`-`3` | the panel's condition fails; the units digit is the shade level |",
             "| `10`-`13` | the condition holds; the units digit is the shade level |",
             "| `10`/`11`, `20`/`21` | stochastic figures: first/second encounter, `1` = collision |",
             "", "## Files", ""]
    for csv in sorted(FIG.rglob("*.csv")):
        header = csv.read_text().splitlines()[0]
        rows = sum(1 for _ in csv.open()) - 1
        flat = csv.parent.name if csv.name == "samples.csv" else f"{csv.parent.name}_{csv.stem}"
        lines.append(f"- `{flat}.csv` — {rows:,} rows: `{header}`")
    return "\n".join(lines) + "\n"


def package():
    """Assemble the folder handed to the paper's authors, and zip it.

    Three ways in, same figures: drop-in PDFs, the TikZ sources with their data, or the
    bare CSVs. ``preview/`` lets them see the figures without compiling anything.
    """
    if PACKAGE.exists():
        shutil.rmtree(PACKAGE)
    (PACKAGE / "csv").mkdir(parents=True)
    for name in ("README.md", "captions.md"):
        shutil.copy(HANDOFF / name, PACKAGE / name)
    shutil.copytree(FIG, PACKAGE / "figures")
    shutil.copytree(OUT / "preview", PACKAGE / "preview") if (OUT / "preview").exists() else None
    (PACKAGE / "preview").mkdir(exist_ok=True)
    for png in sorted(OUT.glob("*.png")):
        shutil.copy(png, PACKAGE / "preview" / png.name)
    if PDFS.exists() and any(PDFS.glob("*.pdf")):
        shutil.copytree(PDFS, PACKAGE / "pdf")
    else:
        print("   note: no PDFs in artifacts/paper/pdf -- packaging without Option 1")
    for csv in sorted(FIG.rglob("*.csv")):                    # the bare tables, named by figure
        stem = csv.parent.name if csv.name == "samples.csv" else f"{csv.parent.name}_{csv.stem}"
        shutil.copy(csv, PACKAGE / "csv" / f"{stem}.csv")
    (PACKAGE / "csv" / "DATA.md").write_text(_data_dictionary())
    archive = shutil.make_archive(str(OUT / "risk_metrics_figures"), "zip",
                                  root_dir=PACKAGE.parent, base_dir=PACKAGE.name)
    return Path(archive)


def main(tokens):
    names = [n for n in FIGURES if not tokens or any(t in n for t in tokens)]
    if not names:
        sys.exit(f"no figure matches {tokens}; available: {', '.join(FIGURES)}")
    OUT.mkdir(parents=True, exist_ok=True)
    write_tikz_templates()
    for name in names:
        fig, notes = FIGURES[name]()
        path = OUT / f"{name}.png"
        fig.savefig(path, dpi=DPI, bbox_inches="tight")
        plt.close(fig)
        print(f"{path.relative_to(OUT.parent.parent)}")
        for line in notes:
            print(f"    {line}")
    print(f"TikZ: {FIG.relative_to(OUT.parent.parent)}/")
    if not tokens:                                   # a full run also repacks the handoff
        archive = package()
        print(f"package: {archive.relative_to(OUT.parent.parent)} "
              f"({archive.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main(sys.argv[1:])
